const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
const GET_DATA_REQUEST = "GET_DATA_REQUEST";
const GET_DATA_FAILURE = "GET_DATA_FAILURE";


const DATA_FILTER_SUCCESS = "DATA_FILTER_SUCCESS";
const DATA_FILTER_REQUEST = "DATA_FILTER_REQUEST";
const DATA_FILTER_FAILURE = "DATA_FILTER_FAILURE";


const DATA_SORT_SUCCESS = "DATA_SORT_SUCCESS";
const DATA_SORT_REQUEST = "DATA_SORT_REQUEST";
const DATA_SORT_FAILURE = "DATA_SORT_FAILURE";






export {GET_DATA_SUCCESS,GET_DATA_REQUEST,GET_DATA_FAILURE,
        DATA_FILTER_SUCCESS,DATA_FILTER_REQUEST,DATA_SORT_FAILURE,
        DATA_FILTER_FAILURE,DATA_SORT_SUCCESS,DATA_SORT_REQUEST}